ALTER TABLE licenses ADD COLUMN IF NOT EXISTS application_fee TEXT;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS timeline TEXT;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS cme_hours INTEGER;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS telehealth_notes TEXT;
